# -*- coding: utf-8 -*-
"""BSI- Algoritmos e programação- atividade 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14qcQze4P7prwPF89kFLt4QQbCUrkEEE8

*   BSI

*   Disciplina: Algoritmos e programação
*   lista de exercicio 1
*   Aluno: Leonardo de Almeida Junior
"""



1# Faça um programa que peça dois números inteiros e imprima a soma desses dois números.

num1 = int(input("digite 1 número para soma: "))
num2 = int(input("digite outro número para soma "))
soma = num1 + num2
print("a soma de", num1, "mais", num2, "é", soma)

2# Escreva um programa que leia um valor em metros e o exiba convertido em milímetros.

convert1 = int(input("digite 1° em metros para a conversão: "))
mult = convert1 * 1000
print("a conversão de", convert1, "m", "para milímitros é", mult, "mm")

3# Escreva um programa que leia a quantidade de dias, horas, minutos e segundos do usuário. Calcule o total em segundos.

dias = float(input("digite o número de dias logado: "))
horas = float(input("digite o número de horas logado: "))
minutos = float(input("ditgite o número de minutos logado: "))
segundos = float(input("digite o número de segundos logado: "))

dias1 = dias * 86400
hora1 = horas * 3600
minutos1 = minutos * 60
resultado = int(dias1 + hora1 + minutos1 + segundos)

print("A soma dos dias + horas + minutos + segundos é igual a: ", resultado)

4# Faça um programa que calcule o aumento de um salário. Ele deve solicitar o valor do salário e a porcentagem do aumento. Exiba o valor do aumento e do novo salário.

sal = float(input("digite o valor do seu salário: "))
por = float(input("digite o valor da porcentagem do aumento do salário: "))
aument2 = (sal * (por / 100)) + sal
print("o valor resultante do aumento de", por, "é", aument2, "reais")

5# Solicite o preço de uma mercadoria e o percentual de desconto. Exiba o valor do desconto e o preço a pagar.

merc = float(input("digite o valor da mercadoria: "))
desc = float(input("digite o valor do desconto: "))
valor1 = merc * (desc / 100)
valor2 = merc - valor1
print(" o valor descontado é", valor1)
print("O novo valor a pagar da mercadoria é: ", valor2)

6# Calcule o tempo de uma viagem de carro. Pergunte a distância a percorrer e a velocidade média esperada para a viagem.

dist = float(input("digite a distância em km: "))
vel = float(input("digite a velocidade em km/h: "))
temp = dist / vel
print("O tempo médio para a viagem é de aproximadamente", temp, "horas")

7# Converta uma temperatura digitada em Celsius para Fahrenheit. F = 9*C/5 + 32 . Faça agora o contrário, de Fahrenheit para Celsius.
cel = float(input("digite o valor dos graus celcius: "))
f = float(9 * cel / 5 + 32)
print(f, "F")
fah = float(input("digite o valor dos graus fahrenheit: "))
c = (fah - 32 / 1,8)
print(c)

8# Escreva um programa que pergunte a quantidade de km percorridos por um carro alugado pelo usuário, assim como a quantidade de dias pelos quais o carro foi alugado. Calcule o preço a pagar, sabendo que o carro custa R$ 60,00 por dia e R$ 0,15 por km rodado.

km = int(input("digite o número de KMs rodados: "))
dia = int(input("digite o número de dias alugado: "))

km1 = km * 0.15
dia1 = dia * 60
devendo = float(km1 + dia1)


print(km1)
print(dia1)
print(devendo)

9# Escreva um programa para calcular a redução do tempo de vida de um fumante. Pergunte a quantidade de cigarros fumados por dia e quantos anos ele já fumou. Considere que um fumante perde 10 minutos de vida a cada cigarro, calcule quantos dias de vida um fumante perderá. Exiba o total de dias.
cig = int(input("digite quantos cigarros fuma por dia? "))
ano = int (input("quantos anos já fumou? "))

cig1 = cig * 0.00694444
ano1 = ano * 365 * 0.00694444
result = int(ano1 +cig1)

print(result)

10# Sabendo que str( ) converte valores numéricos para string, calcule quantos dígitos há em 2 elevado a um milhão.
import sys
sys.set_int_max_str_digits(0)


print(len(str(2 ** 1000000)),"digítos")

print("fim")
