# -*- coding: utf-8 -*-
"""BSI- Algoritmos e programação- atividade 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yTE3j2jBaxfkzTJfKIInXB1l_oHrfN_2
"""

print("Alo mundo")

num = str(input("digite um número: "))
print("O número informado é", num)

num1 = float(input("digite 1° número: "))
num2 = float(input("digite o 2° número: "))
soma = int(num1 + num2)
print(soma)

print("digite as suas notas bimestrais")
not1 = float(input("nota 1: "))
not2 = float(input("nota 2: "))
not3 = float(input("nota 3: "))
not4 = float(input("nota 4: "))
med = (not1 + not2 + not3 + not4)/4
print("sua média é", med)

cem = float(input("digite o tamanho em metros para a conversão: "))
convert = float(cem * 100)
print("A conversão de", cem, "m para centimetros é", convert, "cm")

import math
rai = int(input("digite o número do raio: "))
A = int(math.pi * (rai ** 2))
print("A área do quadrado é", A)

7#
lad = float(input("digite o lado: "))
quad = lad ** 2
quad2 = quad * 2
print(int(quad))
print(int(quad2))

8#
hora = float(input("quanto você ganha por hora? "))
mes = float(input("quantas horas você trabalha por dia? "))
res = hora * mes
print("Você ganha por mês R$",res)

9#
fah = int(input("digite os graus farenheit: "))
C = int(5 * (fah - 32) / 9)
print(C)

10#
cel = int(input("digite os graus farenheit: "))
F = int(((9 * cel)/5) + 32)
print(F)

11# float =número real
int1 = int(input("ditige um número sem casa decimal: "))
int2 = int(input("digite outro número sem casa decimal: "))
real1 = float(input("digite um número com casa decimal"))

A = (2 * int1) * (int2 / 2)
B = (int1 * 3) + real1
C = real1 ** 3

print(A)
print(B)
print(C)

12#
alt = float(input("digite a sua altura: "))
peso = (72.7 * alt) - 58
print("seu peso é", peso)