# -*- coding: utf-8 -*-
"""BSI- Algoritmos e programação- atividade 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KVWb_DYQvj6z2G7iL64cjZEgUw0E2tnH
"""

9#
import math

altura = float(input("digite o altura: "))
raio = float(input("digite o raio: "))

volume = math.pi * (raio ** 2) * altura

print("o volume é:", volume)

10#
nota1 = float(input("digite a 1° nota: "))
nota2 = float(input("digite a 2° nota: "))
nota3 = float(input("digite a 3° nota: "))

media = ((nota1 * 2) + (nota2 * 3) + (nota3 * 5)) / 10

print("a média é:", media)

11#

12#







