# -*- coding: utf-8 -*-
"""BSI- Algoritmos e programação- atividade 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hxEVpqcsXC3TsJk2S8bxTpV8PlHlFM6r
"""

2#
numero = float(input("digite um número: "))

if numero > 0:
  print("é positivo")
else:
  if numero == 0:
    print("é zero")
  else:
    print("é negativo")

3#
numero = float(input("digite um valor: "))

if numero > 10:
  print("É maior que 10!")
else:
  print('É menor que 10!')

4#
numero_1 = float(input("digite um número para soma: "))
numero_2 = float(input("digite outro número para soma: "))

soma = numero_1 + numero_2

if soma > 10:
  print(soma)
else:
  print("reiniciar programa")

5#
numero = float(input("digite um número: "))

divisao = numero % 5

if divisao == 0:
  ("ele é divisivio por 5")
else:
  ("não é divisivio por 5")

6#
numero = float(input("digite um número: "))

if numero < 90 and numero > 20:
  print(f'o número {numero} está entre 20 e 90')
else:
  print("o número não está entre 20 e 90")

7#
idade = int(input("escreva o ano de nascimento: "))
ano_atual = int(input("escreva o ano atual: "))

soma = ano_atual - idade

if soma >= 18:
  print("pode votar")
else:
  print("não pode votar")

8#
idade = int(input("escreva o ano de nascimento: "))
ano_atual = int(input("escreva o ano atual: "))

idade_real = ano_atual - idade

if idade_real >= 0:
  print(f'a idade é {idade_real}')
else:
  str(input("o ano está correto? "))

9#
idade = int(input("digite a sua idade: "))

if idade >= 65:
  print("65 anos ou mais")
else:
  if idade >= 18 and idade < 65:
    print("maior de idade")
  else:
    print("menor de idade")

10#
nota_1 = float(input("digite a nota da 1° avaliação: "))
nota_2 = float(input("digite a nota da 2° avaliação: "))

media = (nota_1 + nota_2) / 2

if media >= 6:
  print(f"aprovado, média {media}")
else:
  print(f"não aprovado, média {media}")

11#
nota_1 = float(input("digite a 1° nota: "))
nota_2 = float(input("digite a 2° nota: "))

media = (nota_1 + nota_2) / 2

if media >= 7:
  print("aprovado")
else:
  exame = float(input(f"sua média é {media} média inferior a 7,0, informe anota do exame: "))
  if exame >= 7:
    print("aprovado")
  else:
    print("reprovado")

12#
prof_1 = int(input("digite o número de horas aula do professor 1: "))
prof_2 = int(input("digite o número de horas aula do professor 2: "))
valor_1 = float(input("digite o valor recebido por hora do professor 1: "))
valor_2 = float(input("digite o valor por hora do professor 2: "))

resultado_1 = prof_1 * valor_1
resultado_2 = prof_2 * valor_2

if resultado_1 > resultado_2:
  print(f'o professor 1 recebe {resultado_1} e recebe mais que o professor 2 ({resultado_2})')
else:
  print(f'o professor 1 recebe {resultado_2} e recebe mais que o professor 2 ({resultado_1})')

13#
numero = int(input("digite um numero inteiro: "))

resultado = numero % 2

if resultado == 0:
  print("é par")
if resultado == 1:
  print("é impar")

14#
time_1 = str(input("escreva o nome do primeiro time: "))
time_2 = str(input("escreva o nome do outro time: "))
gols_1 = int(input("digite o nº de gols feitos do primeiro time: "))
gols_2 = int(input("digite o nº de gols do outro time: "))

if gols_1 > gols_2:
  print(f'{time_1} é o vencedor')
else:
  if gols_1 < gols_2:
    print(f'{time_2} é o vencedor')
  else:
    print("empate")

15#
sigla = str(input("digite a sigla do estado onde mora: "))

if sigla == 'RJ' or 'rj':
  print("Carioca")
else:
    if sigla == 'SP' or 'sp':
        print("Paulista")
    if sigla == "MG" or 'mg':
        print("Mineiro")
    else:
        print("Outros")

16#


17#

25#
# inicial

numero_1 = float(input("digite um número: "))
sinal = str(input("digite o sinal: "))
numero_2 = float(input("digite outro número: "))

# condições

#somar
if sinal == '+':
    resultado = numero_1 + numero_2
else:
 
#subtrair
    if sinal == '-':
        resultado = numero_1 - numero_2

#multiplicar
    if sinal == '*' and 'x':
        resultado = numero_1 * numero_2

#dividir
    if sinal == '/':
        resultado = numero_1 / numero_2

# resultado
(print(resultado))

26#
import math
a = float(input("digite um valor para A: "))
b = float(input("digite um valor para B: "))
c = float(input("digite um valor para C: "))

basca = (b ** 2) - 4 * a * c
basca2 = math.sqrt(basca)
basca_1 = ((- b) + basca2) / 2 * a
basca_2 = ((- b) - basca2) / 2 * a

if basca > 0:
  print(f"a dois resultados, X1 = {basca_1}, X2 = {basca_2}")
else:
  if basca == 0:
    print(f'a apenas um resultado, X = {basca_1}')
  if basca < 0:
    print("não há resultados")

27#
a = int(input("digite um valor para A: "))
b = int(input("digite um valor para B: "))
c = int(input("digite um valor para C: "))



33#
a = int(input("escreva um número: "))
b = int(input("escreva outro número: "))

divisao = a % b
resto = a / b
par_impar_a = a % 2
par_impar_b = b % 2

if divisao == 1:
    soma = a + b
    print(F'a soma é{soma} e o resto é {divisao}')
if divisao == 2:
    if par_impar_a == 1 and par_impar_b == 1:
        print("impar")
        print("impar")
    if par_impar_a == 0 and par_impar_b == 0:
        print("par")
        print("par")
    if par_impar_a == 1 and par_impar_b == 0:
        print("impar")
        print("par")
    if par_impar_a == 0 and par_impar_b == 1:
        print("par")
        print("impar")
if divisao == 3:
    resultado = (a + b) * a
    print(resultado)
if divisao == 4:
    resultado = (a + b) / b
    print(resultado)
else:
    if divisao < 0 or divisao > 4:
        resultado (a + b) ** 2
        print(resultado)

34#
a = int(input("digite a idade do homem A: "))
b = int(input("digite a idade do homem B: "))
c = int(input("digite a idade do mulher A: "))
d = int(input("digite a idade do mulher B: "))

if a > b and c > d:
  resultado_2 = a + c
  resultado_1 = b * d
else:
  if a > b and c < d:
    resultado_2 = a + c
    resultado_1 = b * c
  if a < b and c > d:
    resultado_2 = b + c
    resultado_1 = a * d
  if a < b and c < d:
    resultado_2 = b + d
    resultado_1 = a * c     

print(f'a soma do homem mais velho com a mulher mais velha é {resultado_2}')
print(f'o produto do homem mais novo com a mulher mais nova é {resultado_1}')





















